### ISSUE TITLE
PlugIn not visible in Reaper

### ISSUE THREAD

**Issue by koalastudio72** [ilirbajri/Creatools-piano-xs#1]
Hi ilirbajri,
thank you, first of all, for your hard work and to make it open for everyone, that's very kind.

Unfortunately I found possibly a bug concerning Reaper.
The Plugin can't be found in this DAW.
The vst3-file resides in Programs/Common Files/VST3 after the installation but Reaper doesn't list it.
On the other side, your "Keys"-PlugIn, I also installed, is visible in Reaper and can be played.
Would be great to be able to use "Piano XS" in Reaper.

Thanks a lot in advance.

My configuration:
WIN 10 (22H2)
Reaper 7.22

**Comment by ilirbajri** [comment]
Hi.
Thanks for the report. It is fixed and should work now.

**Comment by koalastudio72** [comment]
Hi ilirbajri,
yes, now it runs in Reaper.
Thank you so much!
